name: driver_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  permission_handler: ^6.1.3
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  firebase_database: ^6.1.2
  fluttertoast: ^8.0.4
  get: ^4.1.4
  provider: ^5.0.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
  fonts:
   - family: regular
     fonts:
       - asset: assets/fonts/bolt-regular.ttf
   - family: semi bold
     fonts:
       - asset: assets/fonts/bolt-semibold.ttf
   - family: Signatra
     fonts:
       - asset: assets/fonts/Signatra.ttf
